# brew services stop postgresql
# docker compose down -v
# docker compose up -d
# docker exec -it rolly-db bash
# psql -U postgres
# \c rollydb
# \l,   \dt
version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: rolly-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rollypostgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

